2024-09-02 11:53:02,633 | INFO  | 'test_run' выполнен успешно 
2024-09-02 11:53:02,633 | ERROR  | Неверный тип данных для объекта Runner 
Traceback (most recent call last):
  File "C:\Users\valentin\PycharmProjects\pythonProject2\tests_12_4.py", line 118, in test_run
    Runner('Вася', -5)
  File "C:\Users\valentin\PycharmProjects\pythonProject2\tests_12_4.py", line 19, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-09-02 11:53:02,634 | ERROR  | Неверный тип данных для объекта Runner 
Traceback (most recent call last):
  File "C:\Users\valentin\PycharmProjects\pythonProject2\tests_12_4.py", line 106, in test_walk
    Runner(2)
  File "C:\Users\valentin\PycharmProjects\pythonProject2\tests_12_4.py", line 14, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
